use_frameworks!

platform :ios, '10.0'

target 'TencentOpenAPI_Swift_Example' do
  pod 'TencentOpenAPI_Swift', :path => '../'

  target 'TencentOpenAPI_Swift_Tests' do
    inherit! :search_paths

    
  end
end
